LOAD DATA LOCAL INFILE '~/CourseDataRan.txt' INTO TABLE Courses LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '~/FacultyDataRan.txt' INTO TABLE Faculty LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '~/TeachDataRan.txt' INTO TABLE Teach LINES TERMINATED BY '\r\n';